# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fairynews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fairynews
  pod 'SnapKit' #, '~> 4.0.0'
  pod 'Alamofire' #, '~> 5.0.0.beta.1'
  pod 'Kingfisher'
  

  target 'fairynewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fairynewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
